
CREATE OR REPLACE TABLE SILVER.ACCOUNTS AS
SELECT
    -- Business Keys
    ACCOUNT_ID,
    CUSTOMER_ID,

    -- Standardized Account Type
    CASE 
        WHEN UPPER(ACCOUNT_TYPE) IN ('CHECKING', 'CURRENT') 
            THEN 'CURRENT'
        WHEN UPPER(ACCOUNT_TYPE) = 'SAVINGS' 
            THEN 'SAVINGS'
        WHEN UPPER(ACCOUNT_TYPE) = 'CREDIT' 
            THEN 'CREDIT'
        ELSE 'UNKNOWN'
    END AS ACCOUNT_TYPE,

    -- Standardized Balance
    CASE 
        WHEN BALANCE IS NULL THEN 0
        WHEN BALANCE < 0 THEN 0
        ELSE BALANCE
    END AS BALANCE,

    -- Metadata
    CURRENT_TIMESTAMP() AS LOAD_TS,
    'BRONZE' AS SOURCE_LAYER

FROM BRONZE.ACCOUNTS

-- Filters
WHERE ACCOUNT_ID IS NOT NULL
  AND CUSTOMER_ID IS NOT NULL
  AND UPPER(ACCOUNT_TYPE) IN ('CHECKING', 'CURRENT', 'SAVINGS', 'CREDIT');
CREATE OR REPLACE TABLE SILVER.ACCOUNTS AS
SELECT
    -- Business Keys
    ACCOUNT_ID,
    CUSTOMER_ID,

    -- Standardize account type (KEEP CHECKING)
    CASE 
        WHEN UPPER(ACCOUNT_TYPE) = 'CHECKING' THEN 'CURRENT'
        WHEN UPPER(ACCOUNT_TYPE) = 'SAVINGS' THEN 'SAVINGS'
        WHEN UPPER(ACCOUNT_TYPE) = 'CREDIT' THEN 'CREDIT'
        WHEN UPPER(ACCOUNT_TYPE) = 'CURRENT' THEN 'CURRENT'
        ELSE 'UNKNOWN'
    END AS ACCOUNT_TYPE,

    -- Standardized Balance
    CASE 
        WHEN BALANCE IS NULL THEN 0
        WHEN BALANCE < 0 THEN 0
        ELSE BALANCE
    END AS BALANCE,

    -- Metadata
    CURRENT_TIMESTAMP() AS LOAD_TS,
    'BRONZE' AS SOURCE_LAYER

FROM BRONZE.ACCOUNTS

-- Filters
WHERE ACCOUNT_ID IS NOT NULL
  AND CUSTOMER_ID IS NOT NULL
  AND UPPER(ACCOUNT_TYPE) IN ('CHECKING', 'SAVINGS', 'CURRENT', 'CREDIT');